### ISSUE TITLE
PS Switch schematics

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai-issues#11]
We shall route PS Switch as analog input if we have an unused analog input

@ElDominio did you say pull-up? what size pull-up?

**Comment by mck1117** [comment]
anything that's a switch will be fine with a 1k-10k pullup, other boards have used 2.7 or 3.3k

**Comment by ElDominio** [comment]
I have previously used a 1k pullup on this switch just fine. It is a digital state switch, activating when PS Pressure goes over a certain amount

**Comment by Qwerty-OFF** [comment]
Connected to IN_SENS1 with a 2.7k pullup
