### ISSUE TITLE
Is 2010 mechanical cable throttle?!

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai-issues#3]
I am looking at wiring differences and it looks like 2014 is ETB

is 2010 mechanical throttle body?

https://github.com/rusefi/rusefi/wiki/Hyundai-Genesis-Coupe

**Comment by ElDominio** [comment]
Nope, both are ETB, pinned the exact same way.

**Comment by rusefillc** [comment]
@ElDominio so https://github.com/rusefi/rusefi/wiki/OEM-Docs/Hyundai/2010-coupe-2.0-5.png is wrong so it could also be wrong in any other way :)

**Comment by ElDominio** [comment]
The diagram I supplied is the one I always use for my PNP kits

https://docs.google.com/spreadsheets/d/1ywuDLkhp-Q8VnNsPLQVZCZtjmalo7IQzmFDbDqwyniM/edit?usp=sharing

Haltech provides it on their manual for their PNP kits

**Comment by rusefillc** [comment]
I was wrong - DC motor I was thinking about is not ETB by wastegate.

Diagrams are perfectly fine
