### ISSUE TITLE
trigger hookup points

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai-issues#5]
Need vias on crank & cam sensor lines for logic analyzer hookup

**Comment by ElDominio** [comment]
Bias voltage? They are both Hall sensors with 5v pullups, Hall sensors pull to ground when metal is near, are open when there isn't.

**Comment by mck1117** [comment]
vias, he means places you can solder a pin or wire to attach a logic analyzer to inspect what's going on in the stock setup.

https://en.wikipedia.org/wiki/Via_(electronics)

**Comment by rusefillc** [comment]
And it looks like crank and all cam sensors are Hall?

**Comment by ElDominio** [comment]
> 
> 
> And it looks like crank and all cam sensors are Hall?

Correct. They pull to ground and float otherwise. I mentioned it before I think

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/hellen121nissan-issues/issues/9

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/129293042-ccdfb4d0-e19f-4258-97c6-b4220186c649.png)

Crank Scope

![image](https://user-images.githubusercontent.com/5685108/129293075-a62141eb-1ac4-4dcb-9909-64b342be5cd0.png)


Cam scope

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/131223391-e46eb79b-a435-4406-be6d-5c9f305afffd.png)
Flipped leds:
![image](https://user-images.githubusercontent.com/4116383/131223419-62baaa25-77cb-435d-901c-c5611ccf087f.png)
