### ISSUE TITLE
Wire wastegate: actuator to use second H-bridge and position sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai-issues#6]
![image](https://user-images.githubusercontent.com/48498823/127775394-98a203a2-ea1e-4ccd-8f8e-a2853b2ecb7d.png)

and we need analog input from position sensor potentiometer

![image](https://user-images.githubusercontent.com/48498823/127775458-c98bc104-fd05-4080-b04f-8c82cf4af13e.png)

**Comment by ElDominio** [comment]
This is  for 2013-2014 engines, 2010-2012 use a traditional wastegate solenoid, just to remind

**Comment by rusefillc** [comment]
@ElDominio what is the pin for 2010-2012 traditional wastegate solenoid?

**Comment by Qwerty-OFF** [comment]
Can we use RZ7899 inside ouput module or we need L6205?

**Comment by rusefillc** [comment]
let's forget about RZ7899 - we are really afraid of it

please use second channel of L6205 it has two channels right?

**Comment by Qwerty-OFF** [comment]
Yes. We connected these channels in parallel in other boards

**Comment by ElDominio** [comment]
> 
> 
> @ElDominio what is the pin for 2010-2012 traditional wastegate solenoid?

It is B47.

Also, B48 is used as the BOV solenoid pin on 2010-2012, I don't know if the same for 2013-2014 (I think so though)

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/hellen121vag/issues/54

I think we can use one channel for ETB and second channel for waste gate

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/131223478-e39ea49f-433b-49b4-ba60-ac509e8b160e.png)
