### ISSUE TITLE
A/C pressure line pin 54

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai-issues#8]
https://github.com/rusefi/rusefi/wiki/Hyundai-Genesis-Coupe#2010

What is it?

Looks like analog signal? really?

![image](https://user-images.githubusercontent.com/48498823/127775591-3e92332a-7d2a-454c-a9c5-f88b4442ee24.png)

**Comment by ElDominio** [comment]
Yep, it is. 
![2021-08-01 11_24_53-Main Setup - BK Theta ECU 1 13](https://user-images.githubusercontent.com/5685108/127776422-7979e98e-ec70-4d84-9e7c-b00ce98d9221.png)

**Comment by Qwerty-OFF** [comment]
Connected to MAP3
![image](https://user-images.githubusercontent.com/4116383/131223522-54bae6bd-57cd-4ca2-b415-2ad17089d3d4.png)
